name: GitHub Actions Demo
on: [push]
jobs:
  Fisrt-Job: # * ชื่อ job
    runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
    steps:
      - run: echo "🎉 Hello KIE"
      - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
        with: # * ตัวแปรที่ส่งไป
          access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
          message: เตรียมวัตถุดิบ หั่นต้นหอม ล้างหมู หั่นหมู
          
   Second-Job: # * ชื่อ job
    runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
    needs: Fisrt-Job
    steps:
      # - run: echo "🎉 Hello KIE"
      - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
        with: # * ตัวแปรที่ส่งไป
          access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
          message: ตั้งไฟ ใส่น้ำมัน ทอดกระเทียมให้หอม

    Third-Job: # * ชื่อ job
      runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
      needs: Second-Job
      steps:
        - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
          with: # * ตัวแปรที่ส่งไป
            access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
            message: ผัดหมูให้สุกใส่ข้าวลงไปผัด ใส่เครื่องปรุง

    Fourth-Job: # * ชื่อ job
      runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
      needs: Third-Job
      steps:
        - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
          with: # * ตัวแปรที่ส่งไป
            access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
            message: ใส่ผัก แล้วตักใส่จาน

    Fifth-Job: # * ชื่อ job
      runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
      needs: Fourth-Job
      steps:
        - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
          with: # * ตัวแปรที่ส่งไป
            access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
            message: ตักใส่ปาก
