name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions: # * ชื่อ job
    runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
    steps:
      - run: echo "🎉 Hello KIE"
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd }}
          message: some message
