# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Fisrt-Job: # * ชื่อ job
#     runs-on: ubuntu-latest # * ชื่อ os ที่ใช้งาน
#     steps:
#       - run: echo "🎉 Hello KIE"
#       - uses: snow-actions/line-notify@v1.0.0 # * ชื่อ lib ของ Line for Github Action
#         with: # * ตัวแปรที่ส่งไป
#           access_token: 0Sm31a2dg4ldVr0w2llNT4aBVGKmldmsVw59QK0UGnd
#           message: 🎉 KIE อัพงานเรียบร้อยแล้ว 🎉
